### ISSUE TITLE
bug: Could not install on Windows

### ISSUE THREAD

**Issue by iKirby** [jef/forest-night-jetbrains#19]
### Problem

Could not install on Windows, tried both IntelliJ IDEA and Android Studio. File is downloaded from JetBrains Plugin Repository.

The error occurred when updating plugins. Then I uninstalled it and tried reinstalling, the same error occurred.

Screenshot:
![Snipaste_2020-08-24_22-41-26](https://user-images.githubusercontent.com/6316115/91059097-e1078400-e65b-11ea-91f8-521541dbeb58.png)

Application: IntelliJ IDEA
Version: 2020.2 Build #IU-202.6397.94

### Expected output

Theme can be installed successfully.

I noticed that there is an invisible character (seems to be LF, it's invisible on Windows) before the extension `.jar`. Removing it allowed me to install the theme successfully. Hope this can be fixed in next version. Thanks.

**Comment by jef** [comment]
Thanks for pointing this out! I will make a fix this week.

**Comment by jef** [comment]
JetBrains says they take couple days to update the plugin, but they usually have pretty quick turn around. Expect `1.1.2` released soon! 🚀

**Comment by jef** [comment]
Hey @iKirby, 1.1.2 was released today. Let me know when you get the chance to update and see if it worked for you!

**Comment by iKirby** [comment]
@jef The new version works well. Thanks for fixing this! (Sorry for the late reply, I was out travelling these days.)

**Comment by jef** [comment]
> Sorry for the late reply

No worries! I appreciate your ticket!
